name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: Install pnpm
      run: |
        npm i pnpm -g
      
    - name: Install dependencies
      run: |
        pnpm i
      env:
        CI: true

#    - name: Lint
#      run: |
#        pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
        
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: Install pnpm
      run: |
        npm i pnpm -g
        
    - name: Install dependencies
      run: |
        pnpm i
      env:
        CI: true

    - name: Run Tests
      run: |
        pnpm run test

  docs:
    needs: [lint, test]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
        
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: Install pnpm
      run: |
        npm i pnpm -g
        
    - name: Install dependencies
      run: |
        pnpm i
      env:
        CI: true

    - name: Create Documentation
      run: |
        pnpm run docs

    - name: Checkout the gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Copy the Documentation
      run: |
        rm -rf gh-pages/master
        mkdir -p gh-pages/master
        cp -r docs gh-pages/master
    
    - name: Push the Documentation
      uses: EndBug/add-and-commit@v4
      with:
        cwd: gh-pages
        ref: gh-pages
        message: Updated the master documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
