name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: Install pnpm
      run: |
        npm i pnpm -g
      
    - name: Install dependencies
      run: |
        pnpm i
      env:
        CI: true

    - name: Lint
      run: |
        pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
        
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: Install pnpm
      run: |
        npm i pnpm -g
        
    - name: Install dependencies
      run: |
        pnpm i
      env:
        CI: true

    - name: Run Tests
      run: |
        pnpm run test
